### ISSUE TITLE
Commands no longer work on 1.19.1 or higher

### ISSUE THREAD

**Issue by gabber235** [dyam0/LirandAPI#1]
# Description
With the introduction of `1.19.1`, Minecraft introduced their new _Player Safety Features_. However this broke something in this command library. When running the `Replicator` in `1.19`. It works as expected. Only when run in `1.19.1` or higher, the console can still execute commands but players commands to register in the console but are not executed. 

Tested on a Macbook with M1 and a PC running linux with a amd64 chip. 

# Replicator
```kotlin
class Replicator : KotlinPlugin() {
	override fun onEnable() {
		command("test") {
			executes {
				// This always get executed for the console. Regardless of the version.
				// But not for players. Then it only runs on version 1.19 or lower.
				source.sendMessage("test")
			}
		}

		listen<PlayerCommandPreprocessEvent> { event ->
			// This is stil works! Even if the command is not executed.
			println("${event.player.name} preprocessed command: ${event.message}")
		}
	}

	override fun onDisable() {
		adventure.close()
	}
}
```

**Comment by dyam0** [comment]
Hi! Fixed by https://github.com/dyam0/LirandAPI/commit/26f60a4baad168d97b38ffcc0160929dd2fbe387.
Thank you for reporting the issue and using this library!
